name: Publish archway to registry
run-name: ${{ github.actor }} run build on ${{ github.repository }}
on:
  push:
    tags:
      - '*'
jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
      - run: mvn -Dmaven.test.skip=true deploy
